<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251210121320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE affiliate_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(1000) NOT NULL, short_code VARCHAR(100) NOT NULL, destination_url VARCHAR(500) DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, tags JSON DEFAULT NULL, total_clicks INT NOT NULL, unique_clicks INT NOT NULL, total_earnings NUMERIC(10, 2) NOT NULL, conversions INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_click_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, program_id INT DEFAULT NULL, site_id INT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4866744C17D2FE0D ON affiliate_link (short_code)');
        $this->addSql('CREATE INDEX IDX_4866744C3EB8070A ON affiliate_link (program_id)');
        $this->addSql('CREATE INDEX IDX_4866744CF6BD1646 ON affiliate_link (site_id)');
        $this->addSql('CREATE INDEX IDX_4866744C7E3C61F9 ON affiliate_link (owner_id)');
        $this->addSql('CREATE TABLE affiliate_program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, website VARCHAR(500) DEFAULT NULL, dashboard_url VARCHAR(500) DEFAULT NULL, network VARCHAR(100) DEFAULT NULL, commission_rate NUMERIC(10, 2) DEFAULT NULL, commission_type VARCHAR(20) DEFAULT NULL, currency VARCHAR(10) DEFAULT NULL, cookie_duration INT DEFAULT NULL, status VARCHAR(50) NOT NULL, category VARCHAR(100) DEFAULT NULL, credentials JSON DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CF0ABCB67E3C61F9 ON affiliate_program (owner_id)');
        $this->addSql('CREATE TABLE click_tracking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_hash VARCHAR(64) NOT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(1000) DEFAULT NULL, country VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, device VARCHAR(50) DEFAULT NULL, browser VARCHAR(50) DEFAULT NULL, os VARCHAR(50) DEFAULT NULL, utm_params JSON DEFAULT NULL, is_unique BOOLEAN NOT NULL, is_conversion BOOLEAN NOT NULL, conversion_value NUMERIC(10, 2) DEFAULT NULL, clicked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, converted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, link_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8031DA65ADA40271 ON click_tracking (link_id)');
        $this->addSql('CREATE INDEX IDX_8031DA65DD3CA9E3 ON click_tracking (clicked_at)');
        $this->addSql('CREATE INDEX IDX_8031DA65C2DF3E37 ON click_tracking (ip_hash)');
        $this->addSql('ALTER TABLE affiliate_link ADD CONSTRAINT FK_4866744C3EB8070A FOREIGN KEY (program_id) REFERENCES affiliate_program (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE affiliate_link ADD CONSTRAINT FK_4866744CF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE affiliate_link ADD CONSTRAINT FK_4866744C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE affiliate_program ADD CONSTRAINT FK_CF0ABCB67E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE click_tracking ADD CONSTRAINT FK_8031DA65ADA40271 FOREIGN KEY (link_id) REFERENCES affiliate_link (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE affiliate_link DROP CONSTRAINT FK_4866744C3EB8070A');
        $this->addSql('ALTER TABLE affiliate_link DROP CONSTRAINT FK_4866744CF6BD1646');
        $this->addSql('ALTER TABLE affiliate_link DROP CONSTRAINT FK_4866744C7E3C61F9');
        $this->addSql('ALTER TABLE affiliate_program DROP CONSTRAINT FK_CF0ABCB67E3C61F9');
        $this->addSql('ALTER TABLE click_tracking DROP CONSTRAINT FK_8031DA65ADA40271');
        $this->addSql('DROP TABLE affiliate_link');
        $this->addSql('DROP TABLE affiliate_program');
        $this->addSql('DROP TABLE click_tracking');
    }
}
